# process names are case-insensitive
# you can use 'master' to indicate the master channel, or a list of process names to create a group
# you can use 'mic' to control your mic input level (uses the default recording device)
# you can use 'deej.unmapped' to control all apps that aren't bound to any slider (this ignores master, system, mic and device-targeting sessions)
# windows only - you can use 'deej.current' to control the currently active app (whether full-screen or not)
# windows only - you can use a device's full name, i.e. "Speakers (Realtek High Definition Audio)", to bind it. this works for both output and input devices
# windows only - you can use 'system' to control the "system sounds" volume
# important: slider indexes start at 0, regardless of which analog pins you're using!
slider_mapping:
  0: master
  1: 
      - sotgame.exe
      - celeste.exe
      - gta5.exe
      - factorio.exe
  2:
      - chrome.exe
      - msedge.exe           #Microsoft edge
  3: whatsapp.exe
  4:
      - discord.exe
      - zoom.exe
  5:
      - spotify.exe
      - twitchui.exe        #twitch client
      - cr.winapp.exe       #crunchyroll
      - netflix.exe

# supported button list https://github.com/micmonay/keybd_event/blob/master/keybd_windows.go (scroll down)
# be sure to convert hex values to decimal (hex values start with 0x)
# for example: to get F13 (0x7C + 0xFFF)
# 0x7C  = 124
# 0xFFF = 4095
# 124 + 4095
# F13 = 4219
# 
# MAKE SURE THE NUMBER OF BUTTONS IN THE CONFIG MATCHES THE NUMBER OF BUTTONS REPORTED BY THE ARDUINO
# If the number of buttons is not the same, deej might crash 
#
button_mapping:
  0: F13
  1: F14
  2: F15
  3: F16
  4: F17
  5: F18
  6: F19
  7: F20
  8: F21
  9: F22
  10: F23
  11: F24

# set this to true if you want the controls inverted (i.e. top is 0%, bottom is 100%)
invert_sliders: false

# settings for connecting to the arduino board
com_port: COM3
baud_rate: 9600

# adjust the amount of signal noise reduction depending on your hardware quality
# supported values are "low" (excellent hardware), "default" (regular hardware) or "high" (bad, noisy hardware)
noise_reduction: low
